name: Destroy

on:
  workflow_dispatch:

jobs:
  Terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_API_TOKEN: ${{ secrets.ARM_CLIENT_SECRET }}
    defaults:
      run:
        working-directory: terraform

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Terraform execution
      - name: Apply Terraform
        run: |
          terraform init
          terraform destroy -auto-approve
